version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: favorite-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: favorite
    ports:
      - "5432:5432"
    volumes:
      - favorite_pgdata:/var/lib/postgresql/data

volumes:
  favorite_pgdata: